version: '3'
services:
  sonarqube-ci-cd:
    image: sonarqube:6.7-alpine
    ports:
      - 9091:9000
      - 9092:9092
    container_name: sonarqube-ci-cd
  jenkins-ci-cd:
    image: getintodevops/jenkins-withdocker:lts-docker18.06.0
    privileged: true
    user: root
    ports:
      - 9090:8080
      - 50000:50000
    container_name: jenkins-ci-cd
    volumes:
      - ./data/jenkins_home:/var/jenkins_home #Remember that, the tmp directory is designed to be wiped on system reboot.
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - sonarqube-ci-cd