version: '3'
services:

  jenkins:
    image: getintodevops/jenkins-withdocker:lts-docker18.06.0
    privileged: true
    user: root
    container_name: jenkins
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ./data/jenkins_home:/var/jenkins_home #Remember that, the tmp directory is designed to be wiped on system reboot.
      - /var/run/docker.sock:/var/run/docker.sock